export const siteConfig = {
  brand: {
    name: "Ethan Gabriel Fernandez",
    heroTitle: "Full-Stack Web Developer & Creative Digital Producer",
    roles: [
      "Full-Stack Web Developer",
      "Frontend Developer (React)",
      "Power Platform Developer",
      "UI/UX Designer",
      "Creative Director - EFX Creations",
      "Videographer & Photographer",
    ],
    intro:
      "I'm Ethan Gabriel Fernandez, a Magna Cum Laude Information Technology graduate specializing in React, .NET, and modern web technologies. I build scalable digital solutions, intuitive user experiences, and creative visual content through my development work and EFX Creations.",
    location: "San Rafael, Bulacan, Philippines",
    availability:
      "Open to Full-Time Opportunities, Freelance Projects, and Technical Collaborations.",
    email: "ethangabrielfernandez@gmail.com",
    resumePath: "/assets/resume/Ethan_Gabriel_Fernandez_Resume.pdf",
    profileImage: "/assets/images/profile/abstract-gradient-profile.svg",
  },
  design: {
    theme: "dark",
    style: "Cyberpunk + Cyber Brutalism + Modern Professional",
    fonts: {
      heading: "Space Grotesk",
      body: "Inter",
      mono: "JetBrains Mono",
    },
    palette: {
      primary: "#00F5FF",
      secondary: "#7C3AED",
      accent: "#FF2E63",
      background: "#0A0A0A",
      surface: "#111111",
      text: "#F8FAFC",
    },
  },
  routes: {
    home: "/",
    about: "/about",
    projects: "/projects",
    webDevelopment: "/projects/web-development",
    projectsEfxRedirect: "/projects/efx-creations",
    projectDetails: "/projects/:slug",
    efxLanding: "/efx-creations",
    efxServices: "/efx-creations/services",
    efxPortfolio: "/efx-creations/portfolio",
    contact: "/contact",
    notFound: "/404",
  },
  navigation: [
    { label: "Home", to: "/" },
    { label: "About", to: "/about" },
    { label: "Projects", to: "/projects" },
    { label: "Web Development", to: "/projects/web-development" },
    { label: "EFX Creations", to: "/efx-creations" },
    { label: "Contact", to: "/contact" },
  ],
  socials: {
    github: "https://github.com/KurrinChi",
    linkedin: "",
    facebook: "",
    instagram: "",
    youtube: "",
    behance: "",
  },
  seo: {
    defaultTitle:
      "Ethan Gabriel Fernandez | Full-Stack Developer & Creative Producer",
    defaultDescription:
      "Magna Cum Laude IT graduate specializing in React, .NET, Power Platform, and creative digital production. Building scalable applications, modern user experiences, and visual content through EFX Creations.",
    siteUrl: "",
    globalOgImage: "/assets/og/global-portfolio-og.svg",
    projectOgImage: "/assets/og/project-og-placeholder.svg",
    defaultKeywords: [
      "Ethan Gabriel Fernandez",
      "Full Stack Developer",
      "React Developer",
      ".NET",
      "Power Platform",
      "EFX Creations",
      "Creative Producer",
    ],
  },
  projects: {
    featured: [
      "selfiegram-photostudios-smart-booking-system",
      "mama-lous-talent-webpage",
      "evergreen-medical-center",
      "efx-creations-portfolio",
    ],
    items: [
      {
        slug: "selfiegram-photostudios-smart-booking-system",
        title: "Selfiegram Photostudios Smart Booking System",
        category: "web-development",
        summary:
          "A full-stack smart booking and management platform designed for photo studio operations with analytics, scheduling automation, and customer experience enhancements.",
        problemSolved:
          "Manual booking workflows, poor customer tracking, and inefficient scheduling management.",
        outcomes: [
          "Smart booking flow",
          "User history tracking",
          "Analytics dashboard",
          "360deg room previews",
          "Improved scheduling efficiency",
        ],
        roles: ["Project Manager", "UI/UX Designer", "Front-End Developer"],
        techStack: ["React", "TypeScript", "Laravel", "MySQL", "Tailwind"],
        features: [
          "Analytics",
          "Booking",
          "360 Preview",
          "Suggestive Booking",
          "User History Tracking",
        ],
        thumbnail: "/assets/images/projects/selfiegram-placeholder.svg",
        gallery: [
          "/assets/images/projects/selfiegram-hero.svg",
          "/assets/images/projects/selfiegram-01.svg",
          "/assets/images/projects/selfiegram-02.svg",
          "/assets/images/projects/selfiegram-03.svg",
        ],
        repoUrl: "",
        liveUrl: "",
        keywords: [
          "smart booking",
          "photo studio",
          "React",
          "Laravel",
          "analytics",
        ],
        ogImage: "/assets/og/project-og-placeholder.svg",
      },
      {
        slug: "mama-lous-talent-webpage",
        title: "Mama Lou's Talent Webpage",
        category: "web-development",
        summary:
          "A React-based talent management platform supporting registration, booking, scheduling, and document management.",
        problemSolved: "Streamlining talent onboarding and booking processes.",
        outcomes: [
          "Multi-step registration",
          "Booking management",
          "Scheduling workflows",
          "MFA implementation",
        ],
        roles: ["Frontend Developer"],
        techStack: ["React", "API Integration"],
        features: [
          "Registration",
          "Booking",
          "Scheduling",
          "MFA",
          "Validation",
        ],
        thumbnail: "/assets/images/projects/mama-lous-placeholder.svg",
        gallery: [
          "/assets/images/projects/mama-lous-hero.svg",
          "/assets/images/projects/mama-lous-01.svg",
          "/assets/images/projects/mama-lous-02.svg",
          "/assets/images/projects/mama-lous-03.svg",
        ],
        repoUrl: "",
        liveUrl: "",
        keywords: ["talent platform", "React", "MFA", "scheduling"],
        ogImage: "/assets/og/project-og-placeholder.svg",
      },
      {
        slug: "evergreen-medical-center",
        title: "Evergreen Medical Center",
        category: "web-development",
        summary: "Hospital management platform built using Java and MySQL.",
        problemSolved:
          "Centralized management of patients, appointments, inventory, rooms, and staff.",
        outcomes: [
          "Real-time record management",
          "Appointment tracking",
          "Inventory monitoring",
          "Administrative efficiency",
        ],
        roles: ["Full-Stack Developer"],
        techStack: ["Java", "MySQL"],
        features: [
          "Hospital Management",
          "Inventory",
          "Patient Tracking",
          "Appointment System",
        ],
        thumbnail: "/assets/images/projects/evergreen-placeholder.svg",
        gallery: [
          "/assets/images/projects/evergreen-hero.svg",
          "/assets/images/projects/evergreen-01.svg",
          "/assets/images/projects/evergreen-02.svg",
          "/assets/images/projects/evergreen-03.svg",
        ],
        repoUrl: "",
        liveUrl: "",
        keywords: ["hospital system", "Java", "MySQL", "inventory"],
        ogImage: "/assets/og/project-og-placeholder.svg",
      },
      {
        slug: "efx-creations-portfolio",
        title: "EFX Creations Portfolio",
        category: "efx-creations",
        summary:
          "A creative portfolio showcase for photography, videography, drone work, and social media campaign content.",
        problemSolved:
          "Presenting multidisciplinary creative work in a single high-impact and client-friendly experience.",
        outcomes: [
          "Service-oriented presentation",
          "Filterable media showcase",
          "Client-focused project storytelling",
        ],
        roles: ["Creative Director", "Videographer", "Photographer"],
        techStack: ["React", "Framer Motion", "Tailwind"],
        features: [
          "Image galleries",
          "Video showcases",
          "Service descriptions",
          "Client highlights",
        ],
        thumbnail: "/assets/images/efx/efx-placeholder.svg",
        gallery: [
          "/assets/images/efx/efx-hero.svg",
          "/assets/images/efx/efx-01.svg",
          "/assets/images/efx/efx-02.svg",
          "/assets/images/efx/efx-03.svg",
        ],
        repoUrl: "",
        liveUrl: "",
        keywords: ["creative portfolio", "photography", "videography", "drone"],
        ogImage: "/assets/og/project-og-placeholder.svg",
      },
    ],
    roadmap: [
      "React Applications",
      "Full Stack Applications",
      "Power Platform Solutions",
      ".NET Applications",
    ],
  },
  efx: {
    services: [
      "Photography",
      "Videography",
      "Video Editing",
      "Drone Coverage",
      "Social Media Content Creation",
      "Event Coverage",
    ],
    filters: [
      "All",
      "Photography",
      "Videography",
      "Drone",
      "Events",
      "Commercial",
      "Social Media",
    ],
    media: [
      {
        id: "efx-photo-01",
        title: "Editorial Night Portraits",
        category: "Photography",
        type: "image",
        thumbnail: "/assets/images/efx/efx-01.svg",
        sourceUrl: "",
      },
      {
        id: "efx-video-01",
        title: "Brand Story Reel",
        category: "Videography",
        type: "youtube",
        thumbnail: "/assets/images/efx/efx-02.svg",
        sourceUrl: "",
      },
      {
        id: "efx-drone-01",
        title: "Aerial Venue Flythrough",
        category: "Drone",
        type: "youtube",
        thumbnail: "/assets/images/efx/efx-03.svg",
        sourceUrl: "",
      },
      {
        id: "efx-event-01",
        title: "Event Coverage Highlights",
        category: "Events",
        type: "image",
        thumbnail: "/assets/images/efx/efx-placeholder.svg",
        sourceUrl: "",
      },
    ],
  },
  about: {
    education: {
      school: "Bulacan State University",
      degree: "Bachelor of Science in Information Technology",
      major: "Major in Web and Mobile Application Development",
      latinHonors: "Magna Cum Laude",
      gpa: "1.28",
    },
    awards: ["Magna Cum Laude", "Dean's Lister", "President's Lister"],
    certifications: [
      "IT Specialist - Software Development",
      "Foundational C#",
      "Cisco Networking",
      "Salesforce Virtual Internship",
    ],
    experience: [
      {
        role: "Frontend Developer Intern",
        stack: ["React", "REST APIs", "Git Collaboration"],
        highlights: ["Performance Improvements"],
      },
      {
        role: "Founder - EFX Creations",
        stack: ["Photography", "Videography", "Editing"],
        highlights: ["Client Management", "Project Delivery"],
      },
    ],
  },
  featureFlags: {
    showParticles: true,
    showScanlines: true,
    showGlassmorphism: true,
    showMagneticButtons: true,
    advancedMotion: true,
    hideEmptyExternalLinks: true,
    hideMissingAssets: true,
  },
};
